import mongoose, { Schema } from 'mongoose'

const profileSchema = new Schema({
    prefix:{
        type:String,
        required:true
    },
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    language:{
        type:String
    },
    uploadImage:{
        type:String
    },
    dateOfBirth:{
        type:Date,
        required:true
    },
    gender:{
        type:String
    },
    maritalStatus:{
        type:String,
        enum:[
            "Married", "Unmarried", "Divorced"
        ]
    },
    bloodGroup:{
        type:String
    },
    mobileNumber:{
        type:Number,
        required:true
    },
    alternateContactNumber:{
        type:Number
    },
    familyContactNumber:{
        type:Number
    },
    facebookLink:{
        type:String
    },
    twitterLink:{
        type:String
    },
    socialMedia1:{
        type:String
    },
    socialMedia2:{
        type:String
    },
    customField1:{
        type:String
    },
    customField2:{
        type:String
    },
    customField3:{
        type:String
    },
    customField4:{
        type:String
    },
    guardianName:{
        type:String
    },
    idProofName:{
        type:String,
        required:true
    },
    idProofNumber:{
        type:String,
        required:true
    },
    permanentAddress:{
        type:String
    },
    currentAddress:{
        type:String
    },
    accountHolderName:{
        type:String
    },
    accountNumber:{
        type:Number
    },
    bankName:{
        type:String
    },
    bankIdentifierCode:{
        type:String
    },
    branch:{
        type:String
    },
    taxPayerID:{
        type:String
    }
})

const Profile = mongoose.model("Profile",profileSchema)
export default Profile