import mongoose, { Schema } from "mongoose";

const roleSchema=new Schema({
    roleName:{
        type:String,
    },
    viewExportButtons:{
        type:Boolean,
        default:false
    },
    viewUser:{
        type:Boolean,
        default:false
    },
    addUser:{
        type:Boolean,
        default:false
    },
    editUser:{
        type:Boolean,
        default:false
    },
    deleteUser:{
        type:Boolean,
        default:false
    },
    viewRole:{
        type:Boolean,
        default:false
    },
    addRole:{
        type:Boolean,
        default:false
    },
    editRole:{
        type:Boolean,
        default:false
    },
    deleteRole:{
        type:Boolean,
        default:false
    },
    viewAllSupplier:{
        type:Boolean,
        default:false
    },
    viewOwnSupplier:{
        type:Boolean,
        default:false
    },
    addSupplier:{
        type:Boolean,
        default:false
    },
    editSupplier:{
        type:Boolean,
        default:false
    },
    deleteSupplier:{
        type:Boolean,
        default:false
    },
    viewAllCustomer:{
        type:Boolean,
        default:false
    },
    viewOwnCustomer:{
        type:Boolean,
        default:false
    },
    viewCustomersWithNoSellFromOneMonthOnly:{
        type:Boolean,
        default:false
    },
    viewCustomersWithNoSellFromThreeMonthsOnly:{
        type:Boolean,
        default:false
    },
    viewCustomersWithNoSellFromSixMonthsOnly:{
        type:Boolean,
        default:false
    },
    viewCustomersWithNoSellFromOneYearOnly:{
        type:Boolean,
        default:false
    },
    viewCustomersIrrespectiveOfTheirSell:{
        type:Boolean,
        default:false
    },
    addCustomer:{
        type:Boolean,
        default:false
    },
    editCustomer:{
        type:Boolean,
        default:false
    },
    deleteCustomer:{
        type:Boolean,
        default:false
    },
    viewProduct:{
        type:Boolean,
        default:false
    },
    addProduct:{
        type:Boolean,
        default:false
    },
    editProduct:{
        type:Boolean,
        default:false
    },
    deleteProduct:{
        type:Boolean,
        default:false
    },
    addOpeningStock:{
        type:Boolean,
        default:false
    },
    viewPurchasePrice:{
        type:Boolean,
        default:false
    },
    viewallPurchaseAndStockAdjustment:{
        type:Boolean,
        default:false
    },
    viewOwnPurchaseAndStockAdjustment:{
        type:Boolean,
        default:false
    },
    addPurchaseAndStockAdjustment:{
        type:Boolean,
        default:false
    },
    editPurchaseAndStockAdjustment:{
        type:Boolean,
        default:false
    },
    deletePurchaseAndStockAdjustment:{
        type:Boolean,
        default:false
    },
    addPurchasePayment:{
        type:Boolean,
        default:false
    },
    editPurchasePayment:{
        type:Boolean,
        default:false
    },
    deletePurchasePayment:{
        type:Boolean,
        default:false
    },
    updateStatus:{
        type:Boolean,
        default:false
    },
    viewPosSell:{
        type:Boolean,
        default:false
    },
    addPosSell:{
        type:Boolean,
        default:false
    },
    editPosSell:{
        type:Boolean,
        default:false
    },
    deletePosSell:{
        type:Boolean,
        default:false
    },
    editProductPriceFromPosScreen:{
        type:Boolean,
        default:false
    },
    editProductDiscountFromPosScreen:{
        type:Boolean,
        default:false
    },
    addOrEditPayment:{
        type:Boolean,
        default:false
    },
    printInvoice:{
        type:Boolean,
        default:false
    },
    disableMultiplePay:{
        type:Boolean,
        default:false
    },
    disableDraft:{
        type:Boolean,
        default:false
    },
    disableExpressCheckout:{
        type:Boolean,
        default:false
    },
    disableDiscount:{
        type:Boolean,
        default:false
    },
    disableSuspendSale:{
        type:Boolean,
        default:false
    },
    disableCreditSaleButton:{
        type:Boolean,
        default:false
    },
    disableQuotation:{
        type:Boolean,
        default:false
    },
    disableCard:{
        type:Boolean,
        default:false
    },
    viewAllSell:{
        type:Boolean,
        default:false
    },
    viewOwnSellOnly:{
        type:Boolean,
        default:false
    },
    viewPaidSellsOnly:{
        type:Boolean,
        default:false
    },
    viewDueSellsOnly:{
        type:Boolean,
        default:false
    },
    viewPartiallyPaidSellsOnly:{
        type:Boolean,
        default:false
    },
    viewOverdueSellsOnly:{
        type:Boolean,
        default:false
    },
    addSell:{
        type:Boolean,
        default:false
    },
    updateSell:{
        type:Boolean,
        default:false
    },
    deleteSell:{
        type:Boolean,
        default:false
    },
    commissionAgentCanViewTheirOwnSell:{
        type:Boolean,
        default:false
    },
    addSellPayment:{
        type:Boolean,
        default:false
    },
    editSellPayment:{
        type:Boolean,
        default:false
    },
    deleteSellPayment:{
        type:Boolean,
        default:false
    },
    editProductPriceFromSalesScreen:{
        type:Boolean,
        default:false
    },
    editProductDiscountFromSaleScreen:{
        type:Boolean,
        default:false
    },
    addOrEditOrDeleteDiscount:{
        type:Boolean,
        default:false
    },
    accessAllSellReturn:{
        type:Boolean,
        default:false
    },
    accessOwnSellReturn:{
        type:Boolean,
        default:false
    },
    addEditInvoiceNumber:{
        type:Boolean,
        default:false
    },
    viewAllDrafts:{
        type:Boolean,
        default:false
    },
    viewOwnDrafts:{
        type:Boolean,
        default:false
    },
    editDraft:{
        type:Boolean,
        default:false
    },
    deleteDraft:{
        type:Boolean,
        default:false
    },
    viewAllQuotations:{
        type:Boolean,
        default:false
    },
    viewOwnQuotations:{
        type:Boolean,
        default:false
    },
    editQuotation:{
        type:Boolean,
        default:false
    },
    deleteQuotation:{
        type:Boolean,
        default:false
    },
    accessAllShipments:{
        type:Boolean,
        default:false
    },
    accessOwnShipments:{
        type:Boolean,
        default:false
    },
    accessPendingShipmentsOnly:{
        type:Boolean,
        default:false
    },
    commissionAgentCanAccessTheirOwnShipments:{
        type:Boolean,
        default:false
    },
    viewCashRegister:{
        type:Boolean,
        default:false
    },
    closeCashRegister:{
        type:Boolean,
        default:false
    },
    viewBrand:{
        type:Boolean,
        default:false
    },
    addBrand:{
        type:Boolean,
        default:false
    },
    editBrand:{
        type:Boolean,
        default:false
    },
    deleteBrand:{
        type:Boolean,
        default:false
    },
    viewTaxRate:{
        type:Boolean,
        default:false
    },
    addTaxRate:{
        type:Boolean,
        default:false
    },
    editTaxRate:{
        type:Boolean,
        default:false
    },
    deleteTaxRate:{
        type:Boolean,
        default:false
    },
    ViewUnit:{
        type:Boolean,
        default:false
    },
    addUnit:{
        type:Boolean,
        default:false
    },
    editUnit:{
        type:Boolean,
        default:false
    },
    deleteUnit:{
        type:Boolean,
        default:false
    },
    ViewCategory:{
        type:Boolean,
        default:false
    },
    addCategory:{
        type:Boolean,
        default:false
    },
    editCategory:{
        type:Boolean,
        default:false
    },
    deleteCategory:{
        type:Boolean,
        default:false
    },
    viewPurchaseAndSellReport:{
        type:Boolean,
        default:false
    },
    viewTaxReport:{
        type:Boolean,
        default:false
    },
    viewSupplierAndCustomerReport:{
        type:Boolean,
        default:false
    },
    viewExpenseReport:{
        type:Boolean,
        default:false
    },
    viewProfitOrLossReport:{
        type:Boolean,
        default:false
    },
    viewStockReportAndstockAdjustmentReportAndStockExpiryReport:{
        type:Boolean,
        default:false
    },
    viewTrendingProductReport:{
        type:Boolean,
        default:false
    },
    viewRegisterReport:{
        type:Boolean,
        default:false
    },
    viewSalesRepresentativeReport:{
        type:Boolean,
        default:false
    },
    viewProductStockValue:{
        type:Boolean,
        default:false
    },
    accessBusinessSettings:{
        type:Boolean,
        default:false
    },
    accessBarcodeSettings:{
        type:Boolean,
        default:false
    },
    AccessInvoiceSettings:{
        type:Boolean,
        default:false
    },
    accessPrinters:{
        type:Boolean,
        default:false
    },
    accessAllExpenses:{
        type:Boolean,
        default:false
    },
    viewOwnExpenseOnly:{
        type:Boolean,
        default:false
    },
    addExpense:{
        type:Boolean,
        default:false
    },
    editExpense:{
        type:Boolean,
        default:false
    },
    deleteExpense:{
        type:Boolean,
        default:false
    },
viewHomeData:{
        type:Boolean,
        default:false
    },
    accessAccounts:{
        type:Boolean,
        default:false
    },
    editAccountTransaction:{
        type:Boolean,
        default:false
    },
    deleteAccountTransaction:{
        type:Boolean,
        default:false
    },
    defaultSellingPrice:{
        type:Boolean,
        default:false
    },
    accessAccountingModule:{
        type:Boolean,
        default:false
    },
    manageAccounts:{
        type:Boolean,
        default:false
    },
    viewJournal:{
        type:Boolean,
        default:false
    },
    addJournal:{
        type:Boolean,
        default:false
    },
    editJournal:{
        type:Boolean,
        default:false
    },
    deleteJournal:{
        type:Boolean,
        default:false
    },
    mapTransactions:{
        type:Boolean,
        default:false
    },
    viewTransfer:{
        type:Boolean,
        default:false
    },
    addTransfer:{
        type:Boolean,
        default:false
    },
    editTransfer:{
        type:Boolean,
        default:false
    },
    deleteTransfer:{
        type:Boolean,
        default:false
    },
    manageBudget:{
        type:Boolean,
        default:false
    },
    viewReports:{
        type:Boolean,
        default:false
    },
    accessAllFollowUp:{
        type:Boolean,
        default:false
    },
    accessOwnFollowUp:{
        type:Boolean,
        default:false
    },
    accessAllLeads:{
        type:Boolean,
        default:false
    },
    accessOwnLeads:{
        type:Boolean,
        default:false
    },
    accessAllCampaigns:{
        type:Boolean,
        default:false
    },
    accessOwnCampaigns:{
        type:Boolean,
        default:false
    },
    AccessContactLogin:{
        type:Boolean,
        default:false
    },
    accessSources:{
        type:Boolean,
        default:false
    },
    accessLifeStage:{
        type:Boolean,
        default:false
    },
    accessProposal:{
        type:Boolean,
        default:false
    },
    AddOrEditOrViewOrDeleteLeaveType:{
        type:Boolean,
        default:false
    },
    AddOrEditOrViewOrDeleteAllLeave:{
        type:Boolean,
        default:false
    },
    addOrViewOwnLeave:{
        type:Boolean,
        default:false
    },
    approveLeave:{
        type:Boolean,
        default:false
    },
    addOrEditOrViewOrDeleteAllAttendance:{
        type:Boolean,
        default:false
    },
    viewOwnAttendance:{
        type:Boolean,
        default:false
    },
    allowUsersToEnterTheirOwnAttendanceFromWeb:{
        type:Boolean,
        default:false
    },
    allowUsersToEnterTheirOwnAttendanceFromApi:{
        type:Boolean,
        default:false
    },
    viewPayComponent:{
        type:Boolean,
        default:false
    },
    addPayComponent:{
        type:Boolean,
        default:false
    },
    addOrEditOrViewOrDeleteDepartment:{
        type:Boolean,
        default:false
    },
    addOrEditOrViewOrDeleteDesignation:{
        type:Boolean,
        default:false
    },
    viewAllPayroll:{
        type:Boolean,
        default:false
    },
    addPayroll:{
        type:Boolean,
        default:false
    },
    editPayroll:{
        type:Boolean,
        default:false
    },
    deletePayroll:{
        type:Boolean,
        default:false
    },
    assignToDosToOthers:{
        type:Boolean,
        default:false
    },
    addToDos:{
        type:Boolean,
        default:false
    },
    editToDos:{
        type:Boolean,
        default:false
    },
    deleteToDos:{
        type:Boolean,
        default:false
    },
    createMessage:{
        type:Boolean,
        default:false
    },
    viewMessage:{
        type:Boolean,
        default:false
    },
    accessSalesTargets:{
        type:Boolean,
        default:false
    },
    addInvoice:{
        type:Boolean,
        default:false
    },
    editInvoice:{
        type:Boolean,
        default:false
    },
    viewAllInvoice:{
        type:Boolean,
        default:false
    },
    viewOwnInvoice:{
        type:Boolean,
        default:false
    },
    deleteInvoice:{
        type:Boolean,
        default:false
    },
    changeInvoiceStatus:{
        type:Boolean,
        default:false
    },
    addOrEditOrDeleteJobSheetStatus:{
        type:Boolean,
        default:false
    },
    addJobSheet:{
        type:Boolean,
        default:false
    },
    editJobSheet:{
        type:Boolean,
        default:false
    },
    deleteJobSheet:{
        type:Boolean,
        default:false
    },
    viewOnlyAssignedJobSheet:{
        type:Boolean,
        default:false
    },
    viewAllJobSheets:{
        type:Boolean,
        default:false
    },
    accessPackageSubscriptions:{
        type:Boolean,
        default:false
    },
   
},{timestamps:true})

const Role=mongoose.model("Role",roleSchema)
export default Role;